version: '3.8'

services:
  backend:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
    command: npm run dev
